### ISSUE TITLE
[NumberGuesser] Использование имени пользователя

### ISSUE THREAD

**Issue by pavel-b-novikov** [Phoenix-616/nsudotnet#1]
Сделайте так, чтобы имя пользователя появлялось в ругательствах

**Comment by Phoenix-616** [comment]
Не совсем понимаю. Имя пользователя добавляется к ругательствам (Console.WriteLine(sentence[rand.Next(sentence.Length)] + player)). И это вроде работает

**Comment by pavel-b-novikov** [comment]
Ну а в середину ругательства?

**Comment by Phoenix-616** [comment]
Добавил, использовал String.format();

**Comment by pavel-b-novikov** [comment]
Другое дело
