### ISSUE TITLE
[LinesCounter] Replace

### ISSUE THREAD

**Issue by pavel-b-novikov** [Phoenix-616/nsudotnet#10]
```str = str.Replace(Environment.NewLine, "");```

Простите, что делает этот дзен-код?

**Comment by Phoenix-616** [comment]
Удаляет символы переноса строки

**Comment by Phoenix-616** [comment]
информационная ценность строки оценивалась по остатку после удаления whitespace и комментариев. если получалась пустая строка, то она пропускается

**Comment by Phoenix-616** [comment]
Я читал документацию по ReadLine(). Там написано, что символы переноса строки в возвращаемой строке отсутствуют, но без этой строки код не работал, пустые строки файла не распознавались как пустые

**Comment by Phoenix-616** [comment]
Признаю, был не прав. Работает. Видимо накладывалось на что-то другое

**Comment by Phoenix-616** [comment]
Залил новую версию
