### ISSUE TITLE
[LinesCounter] Лишние строки

### ISSUE THREAD

**Issue by pavel-b-novikov** [Phoenix-616/nsudotnet#11]
Сколько лишних строк создает ваша программа? Сколько максимум лишних строк подобная программа должна создавать?

**Comment by Phoenix-616** [comment]
1.  удаление переноса
2. сплитинг (кол-во отдельных слов в строке) (можно было обойтись бы String.Trim(), если бы он удалял все whitespace)
3. удаление каждого комментария порождает новую строку

Теоретически, можно обойтись без порождения новых строк, если разбирать строку по символам. Как прикрутить сюда регулярные выражения я не придумал

**Comment by Phoenix-616** [comment]
Избавился от сплита и последующего Join()

**Comment by pavel-b-novikov** [comment]
Зачем регулярные выражения-то, блин?
Ну отлично, вы использовали Remove. Количество порожденных строк не изменилось

**Comment by Phoenix-616** [comment]
Переписал на substring(). Эта функция вызывает внутри себя копирование строк единожды, в отличие от remove()

**Comment by pavel-b-novikov** [comment]
В смысле? А зачем remove вызвать копирование дважды?

**Comment by Phoenix-616** [comment]
Копируется часть строки до удаляемой части и часть после
Информацию взял отсюда
https://stackoverflow.com/questions/34187988/c-sharp-string-substring-or-string-remove

**Comment by pavel-b-novikov** [comment]
А, вы этом смысле.. Это да. 
Эту задачу можно решить вообще без копирования строк?

**Comment by Phoenix-616** [comment]
Можно обнаруживать промежутки в строке без комментариев и посимвольно проверять их на наличие символов отличных от whitespace

**Comment by pavel-b-novikov** [comment]
Давайте уговоримся на том, что у вас в зачетке будет 4
