### ISSUE TITLE
[NumberGuesser] LinkedList

### ISSUE THREAD

**Issue by pavel-b-novikov** [Phoenix-616/nsudotnet#4]
Обоснуйте необходимость использовать LinkedList, какие еще варианты есть и чем LinkedList от них отличается?

**Comment by Phoenix-616** [comment]
Собственно, можно (и нужно было) использовать List<E>. LinkedList<T> разумно использовать, когда ожидаются множественные вставки в середину списка. Использовал LinkedList, потому что java...
Исправил

**Comment by pavel-b-novikov** [comment]
А в java что использовали?

**Comment by Phoenix-616** [comment]
В java LinkedList, обычно приходится часто вставлять/удалять элементы из середины

**Comment by pavel-b-novikov** [comment]
Боюсь представить что вы пишете, если вам приходится вставлять элементы в середину. Уж не персистентные ли структуры данных?
