### ISSUE TITLE
[Enigma] getFileName

### ISSUE THREAD

**Issue by pavel-b-novikov** [Phoenix-616/nsudotnet#6]
Неправильный подход. Переделайте

**Comment by Phoenix-616** [comment]
Через Path.GetExtension() будет лучше?

**Comment by pavel-b-novikov** [comment]
Нет, есть вариант еще лучше

**Comment by Phoenix-616** [comment]
Path.GetFileNameWithoutExtension(path)
Так?

**Comment by pavel-b-novikov** [comment]
А полный путь к файлу слабо собрать нормально?

**Comment by Phoenix-616** [comment]
Path.ChangeExtension()
Исправил
