### ISSUE TITLE
[Enigma] Диспоз

### ISSUE THREAD

**Issue by pavel-b-novikov** [Phoenix-616/nsudotnet#7]
Ни один из используемых классов не диспозится. Это неправильно. Переделайте

**Comment by Phoenix-616** [comment]
Исправил

**Comment by pavel-b-novikov** [comment]
нет, вы диспозите не все

**Comment by Phoenix-616** [comment]
Все (кажется) объекты с интерфейсом IDisposable создаются через using

**Comment by pavel-b-novikov** [comment]
теперь вижу
